### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by micdech** [tipudanny/loyalty-card-system#9]
if i try to login with two users inside seed can't do that.

Is there a way to login in this app?

**Comment by tipudanny** [comment]
yes, you can do .

**Comment by tipudanny** [comment]
please check you seeder code and try again. thanks

**Comment by tipudanny** [comment]
you can try this link : http://loyalty.tipu.me/
username: danny@gmail.com
password: 12345678

**Comment by tipudanny** [comment]
close
